export const POSITIVE_KEYWORDS: readonly string[] = [
  'FullStack',
  'Full-Stack',
  'Next.js',
  'Front-End',
  'Tailwind',
  'NestJS',
  'Node.js',
  'Nodejs',
  'Node',
  'MySQL',
  'Postgres',
  'SQL',
  'Docker',
  'CI/CD',
  'Storybook',
  'Playwright',
  'Full Stack',
  'TypeScript',
  'React.js',
  'React',
  'React Native',
  'Java',
  'Spring',
  'Boot',
  'ChatGPT',
  'S3',
  'ReactJS',
  'microservicios',
  'HTML5',
  'CSS3',
  'PostgreSQL',
  'MongoDB',
  'JavaScript',
  'Redux',
  'Python',
  'Django',
  'AWS',
  'EC2',
  'Aurora',
  'RDS',
  'DynamoDB',
  'Lambdas',
  'Microservices',
  'Serverless',
  'Architecture',
  'Micro-frontend',
  'Frontend',
  'Development',
  'Backend',
  'Spec-driven',
  'SDD',
  'Database',
  'Migration',
  'Legacy',
  'System',
  'Reports',
  'Dashboard',
  'Performance',
  'Optimization',
  'Application',
  'Production',
  'On-call',
  'React',
  'Chart',
  'Library',
  'Remote',
  'US',
  'HTML',
  'CSS',
  'Tailwind',
  'LATAM',
  'Timezone',
  'GraphQL',
  'English',
  'B2',
  'Spanish',
  'Certifications',
  'Senior',
  'Self-taught',
  'Radix UI',
  'TanStack Query',
  'Zustand',
  'Framer Motion',
  'JIRA',
  'Recharts',
  'Lucide',
  'NextJs',
];

export const NEGATIVE_KEYWORDS: readonly string[] = [
  'Angular',
  'assure',
  'Azure',
  'Kubernetes',
  'Distributed Systems',
  'Wordpress',
  'Microsoft Azure',
  'vue',
  'rust',
  'Ruby',
  'Ruby on Rails',
  'Rails',
  'swift',
  'c++',
  'c#',
  'Tech Lead',
  'Tech-Lead',
  'Technical Lead',
  'Team Lead',
  'Golang',
  'IONIC',
  '.net',
  'PHP',
  'Kotlin',
  'Android',
  'iOS',
  'mobile',
  'prisma',
  'flutter',
  'dart',
  'magento',
  'Firebase Cloud Functions v2',
  'Firebase Auth',
  'Cloud Firestore',
  'Cloud Storage',
  'Cloud Run',
  'Cloud Tasks',
  'Cloud Scheduler',
  'Google Cloud Secret Manager',
  'Google',
  'Webflow',
  'Shopify',
];

export const ORANGE_KEYWORDS: readonly string[] = [
  'Principal',
  'exclusive',
  'excluyent',
  'React Native',
  'exclusivo',
  'Expo',
  'RabbitMQ',
  'EventBridge',
  'Lambda',
  'Event Bridge',
  'SNS',
  'exclusiva',
  'excluyente',
  'Bachelor',
  'Express',
];

export const PURPLE_KEYWORDS: readonly string[] = [
  'Artificial Intelligence',
  'Natural Language Processing',
  'Agentic',
  'Agents',
  'Agent',
  'AI',
  'Assisted',
  'Chatbot',
  'Natural Language',
  'Processing',
  'MCP',
  'Claude',
  'Opencode',
  'Cursor',
  'Codex',
];
