/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Login */
    post: operations['login_api_v1_auth_login_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/register': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Register */
    post: operations['register_api_v1_auth_register_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/refresh': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Refresh */
    post: operations['refresh_api_v1_auth_refresh_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Logout */
    post: operations['logout_api_v1_auth_logout_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/user': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get User */
    get: operations['get_user_api_v1_user_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/session': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Session */
    get: operations['get_session_api_v1_session_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/profiles': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Profiles Endpoint */
    get: operations['list_profiles_endpoint_api_v1_profiles_get'];
    put?: never;
    /** Create Profile Endpoint */
    post: operations['create_profile_endpoint_api_v1_profiles_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/profiles/{profileId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Profile Endpoint */
    get: operations['get_profile_endpoint_api_v1_profiles__profileId__get'];
    /** Update Profile Endpoint */
    put: operations['update_profile_endpoint_api_v1_profiles__profileId__put'];
    post?: never;
    /** Archive Profile Endpoint */
    delete: operations['archive_profile_endpoint_api_v1_profiles__profileId__delete'];
    options?: never;
    head?: never;
    /** Rename Profile Endpoint */
    patch: operations['rename_profile_endpoint_api_v1_profiles__profileId__patch'];
    trace?: never;
  };
  '/api/v1/profiles/{profileId}/versions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Versions Endpoint */
    get: operations['list_versions_endpoint_api_v1_profiles__profileId__versions_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/profiles/{profileId}/versions/{version}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Version Endpoint */
    get: operations['get_version_endpoint_api_v1_profiles__profileId__versions__version__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/profiles/{profileId}/versions/{version}/activate': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Activate Version Endpoint */
    post: operations['activate_version_endpoint_api_v1_profiles__profileId__versions__version__activate_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health */
    get: operations['health_health_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** ApiResponse[AuthResponse] */
    ApiResponse_AuthResponse_: {
      /** Message */
      message: string;
      /** Status */
      status: string;
      /**
       * Date
       * Format: date-time
       */
      date?: string;
      response?: components['schemas']['AuthResponse'] | null;
    };
    /** ApiResponse[ProfileMetadata] */
    ApiResponse_ProfileMetadata_: {
      /** Message */
      message: string;
      /** Status */
      status: string;
      /**
       * Date
       * Format: date-time
       */
      date?: string;
      response?: components['schemas']['ProfileMetadata'] | null;
    };
    /** ApiResponse[ProfileSnapshot] */
    ApiResponse_ProfileSnapshot_: {
      /** Message */
      message: string;
      /** Status */
      status: string;
      /**
       * Date
       * Format: date-time
       */
      date?: string;
      response?: components['schemas']['ProfileSnapshot'] | null;
    };
    /** ApiResponse[ProfileVersionSnapshot] */
    ApiResponse_ProfileVersionSnapshot_: {
      /** Message */
      message: string;
      /** Status */
      status: string;
      /**
       * Date
       * Format: date-time
       */
      date?: string;
      response?: components['schemas']['ProfileVersionSnapshot'] | null;
    };
    /** ApiResponse[UserResponse] */
    ApiResponse_UserResponse_: {
      /** Message */
      message: string;
      /** Status */
      status: string;
      /**
       * Date
       * Format: date-time
       */
      date?: string;
      response?: components['schemas']['UserResponse'] | null;
    };
    /** ApiResponse[list[ProfileMetadata]] */
    ApiResponse_list_ProfileMetadata__: {
      /** Message */
      message: string;
      /** Status */
      status: string;
      /**
       * Date
       * Format: date-time
       */
      date?: string;
      /** Response */
      response?: components['schemas']['ProfileMetadata'][] | null;
    };
    /** ApiResponse[list[ProfileVersionMetadata]] */
    ApiResponse_list_ProfileVersionMetadata__: {
      /** Message */
      message: string;
      /** Status */
      status: string;
      /**
       * Date
       * Format: date-time
       */
      date?: string;
      /** Response */
      response?: components['schemas']['ProfileVersionMetadata'][] | null;
    };
    /** AuthResponse */
    AuthResponse: {
      /** Token */
      token: string;
      user: components['schemas']['UserResponse'];
    };
    /** CandidateProfileV1 */
    CandidateProfileV1: {
      /**
       * Schemaversion
       * @constant
       */
      schemaVersion: 1;
      /** Locale */
      locale: string;
      personalInfo: components['schemas']['PersonalInfo'];
      /** Defaultrole */
      defaultRole?: string | null;
      /** Basesummary */
      baseSummary?: string | null;
      /** Experience */
      experience: components['schemas']['Experience'][];
      /** Skills */
      skills: components['schemas']['Skill'][];
      /** Languages */
      languages: components['schemas']['Language'][];
      /** Education */
      education: components['schemas']['Education'][];
      /** Projects */
      projects: components['schemas']['Project'][];
      /** Certifications */
      certifications: components['schemas']['Certification'][];
    };
    /** Certification */
    Certification: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string;
      /** Issuer */
      issuer: string;
      /** Issuedate */
      issueDate?: string | null;
      /** Expirationdate */
      expirationDate?: string | null;
      /** Credentialid */
      credentialId?: string | null;
      /** Credentialurl */
      credentialUrl?: string | null;
    };
    /**
     * CreateProfileRequest
     * @example {
     *       "name": "Backend",
     *       "profile": {
     *         "certifications": [],
     *         "education": [],
     *         "experience": [],
     *         "languages": [],
     *         "locale": "en-US",
     *         "personalInfo": {
     *           "email": "ada@example.com",
     *           "fullName": "Ada Lovelace",
     *           "links": []
     *         },
     *         "projects": [],
     *         "schemaVersion": 1,
     *         "skills": []
     *       }
     *     }
     */
    CreateProfileRequest: {
      /** Name */
      name: string;
      profile: components['schemas']['CandidateProfileV1'];
    };
    /** Education */
    Education: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Institution */
      institution: string;
      /** Degree */
      degree?: string | null;
      /** Fieldofstudy */
      fieldOfStudy?: string | null;
      location?: components['schemas']['Location'] | null;
      /** Startdate */
      startDate?: string | null;
      /** Enddate */
      endDate?: string | null;
    };
    /**
     * EmploymentType
     * @enum {string}
     */
    EmploymentType:
      'full-time' | 'part-time' | 'contract' | 'freelance' | 'internship';
    /** ErrorResponse */
    ErrorResponse: {
      /** Detail */
      detail: string;
    };
    /** Experience */
    Experience: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Company */
      company: string;
      companyLocation?: components['schemas']['Location'] | null;
      /** Position */
      position: string;
      employmentType?: components['schemas']['EmploymentType'] | null;
      locationType?: components['schemas']['LocationType'] | null;
      /** Startdate */
      startDate: string;
      /** Enddate */
      endDate?: string | null;
      /** Summary */
      summary?: string | null;
      /** Responsibilities */
      responsibilities?: string[] | null;
      /** Achievements */
      achievements: string[];
      /** Skillrefs */
      skillRefs: string[];
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][];
    };
    /** Language */
    Language: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Language */
      language: string;
      proficiency: components['schemas']['LanguageProficiency'];
    };
    /**
     * LanguageProficiency
     * @enum {string}
     */
    LanguageProficiency: 'native' | 'C2' | 'C1' | 'B2' | 'B1' | 'A2' | 'A1';
    /** Link */
    Link: {
      type: components['schemas']['LinkType'];
      /** Url */
      url: string;
      /** Label */
      label?: string | null;
    };
    /**
     * LinkType
     * @enum {string}
     */
    LinkType: 'portfolio' | 'linkedin' | 'github' | 'other';
    /** Location */
    Location: {
      /** City */
      city?: string | null;
      /** Region */
      region?: string | null;
      /** Countrycode */
      countryCode?: string | null;
      /** Timezone */
      timezone?: string | null;
    };
    /**
     * LocationType
     * @enum {string}
     */
    LocationType: 'onsite' | 'hybrid' | 'remote';
    /** LoginRequest */
    LoginRequest: {
      /** Username */
      username: string;
      /** Password */
      password: string;
    };
    /** PersonalInfo */
    PersonalInfo: {
      /** Fullname */
      fullName: string;
      /**
       * Email
       * Format: email
       */
      email: string;
      /** Phone */
      phone?: string | null;
      location?: components['schemas']['Location'] | null;
      /** Links */
      links: components['schemas']['Link'][];
    };
    /** ProfileMetadata */
    ProfileMetadata: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string;
      /** Currentversion */
      currentVersion: number;
      /**
       * Createdat
       * Format: date-time
       */
      createdAt: string;
      /**
       * Updatedat
       * Format: date-time
       */
      updatedAt: string;
    };
    /** ProfileSnapshot */
    ProfileSnapshot: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string;
      /** Currentversion */
      currentVersion: number;
      /**
       * Createdat
       * Format: date-time
       */
      createdAt: string;
      /**
       * Updatedat
       * Format: date-time
       */
      updatedAt: string;
      profile: components['schemas']['CandidateProfileV1'];
    };
    /**
     * ProfileSourceType
     * @enum {string}
     */
    ProfileSourceType: 'MANUAL' | 'RESUME_PARSE' | 'IMPORT';
    /** ProfileVersionMetadata */
    ProfileVersionMetadata: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Versionnumber */
      versionNumber: number;
      /** Schemaversion */
      schemaVersion: number;
      sourceType: components['schemas']['ProfileSourceType'];
      /**
       * Createdat
       * Format: date-time
       */
      createdAt: string;
      /** Iscurrent */
      isCurrent: boolean;
    };
    /** ProfileVersionSnapshot */
    ProfileVersionSnapshot: {
      /**
       * Profileid
       * Format: uuid
       */
      profileId: string;
      /** Name */
      name: string;
      version: components['schemas']['ProfileVersionMetadata'];
      profile: components['schemas']['CandidateProfileV1'];
    };
    /** Project */
    Project: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string;
      /** Role */
      role?: string | null;
      /** Description */
      description: string;
      /** Startdate */
      startDate?: string | null;
      /** Enddate */
      endDate?: string | null;
      /** Url */
      url?: string | null;
      /** Repository */
      repository?: string | null;
      /** Achievements */
      achievements?: string[] | null;
      /** Skillrefs */
      skillRefs?: string[] | null;
    };
    /** RegisterRequest */
    RegisterRequest: {
      /** Email */
      email: string;
      /** Username */
      username: string;
      /** Password */
      password: string;
    };
    /** RenameProfileRequest */
    RenameProfileRequest: {
      /** Name */
      name: string;
    };
    /** Skill */
    Skill: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string;
      /** Category */
      category: string;
      /** Aliases */
      aliases?: string[] | null;
      /** Yearsofexperience */
      yearsOfExperience?: number | null;
      /** Lastused */
      lastUsed?: string | null;
      /** Evidencerefs */
      evidenceRefs?: string[] | null;
    };
    /** UpdateProfileRequest */
    UpdateProfileRequest: {
      /** Expectedversion */
      expectedVersion: number;
      profile: components['schemas']['CandidateProfileV1'];
    };
    /** UserResponse */
    UserResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Email */
      email: string;
      /** Username */
      username: string;
      /** Accountverified */
      accountVerified: boolean;
      /** Role */
      role: string;
      /**
       * Createdat
       * Format: date-time
       */
      createdAt: string;
      /**
       * Updatedat
       * Format: date-time
       */
      updatedAt: string;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  login_api_v1_auth_login_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiResponse_AuthResponse_'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  register_api_v1_auth_register_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RegisterRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiResponse_AuthResponse_'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  refresh_api_v1_auth_refresh_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: {
        refresh_token?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiResponse_AuthResponse_'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  logout_api_v1_auth_logout_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  get_user_api_v1_user_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiResponse_UserResponse_'];
        };
      };
    };
  };
  get_session_api_v1_session_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiResponse_UserResponse_'];
        };
      };
    };
  };
  list_profiles_endpoint_api_v1_profiles_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiResponse_list_ProfileMetadata__'];
        };
      };
    };
  };
  create_profile_endpoint_api_v1_profiles_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateProfileRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiResponse_ProfileSnapshot_'];
        };
      };
      /** @description Conflict: duplicate name, stale version, or archived profile */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Invalid request body */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  get_profile_endpoint_api_v1_profiles__profileId__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        profileId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiResponse_ProfileSnapshot_'];
        };
      };
      /** @description Profile not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  update_profile_endpoint_api_v1_profiles__profileId__put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        profileId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateProfileRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiResponse_ProfileSnapshot_'];
        };
      };
      /** @description Profile not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Conflict: duplicate name, stale version, or archived profile */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Invalid request body */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  archive_profile_endpoint_api_v1_profiles__profileId__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        profileId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Profile not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  rename_profile_endpoint_api_v1_profiles__profileId__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        profileId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RenameProfileRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiResponse_ProfileMetadata_'];
        };
      };
      /** @description Profile not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Conflict: duplicate name, stale version, or archived profile */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Invalid request body */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  list_versions_endpoint_api_v1_profiles__profileId__versions_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        profileId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiResponse_list_ProfileVersionMetadata__'];
        };
      };
      /** @description Profile not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_version_endpoint_api_v1_profiles__profileId__versions__version__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        profileId: string;
        version: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiResponse_ProfileVersionSnapshot_'];
        };
      };
      /** @description Profile not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  activate_version_endpoint_api_v1_profiles__profileId__versions__version__activate_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        profileId: string;
        version: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiResponse_ProfileSnapshot_'];
        };
      };
      /** @description Profile not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Conflict: duplicate name, stale version, or archived profile */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  health_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            [key: string]: string;
          };
        };
      };
    };
  };
}
