import {
  LuAward,
  LuBriefcase,
  LuCheck,
  LuChevronDown,
  LuChevronUp,
  LuCodeXml,
  LuContact,
  LuFileText,
  LuFolderKanban,
  LuGraduationCap,
  LuGripVertical,
  LuHistory,
  LuHouse,
  LuLanguages,
  LuLogOut,
  LuMenu,
  LuPlus,
  LuTrash2,
  LuUser,
  LuX,
} from 'react-icons/lu';

export const ICON_COMPONENTS = {
  home: LuHouse,
  profile: LuUser,
  logout: LuLogOut,
  check: LuCheck,
  chevronDown: LuChevronDown,
  chevronUp: LuChevronUp,
  add: LuPlus,
  delete: LuTrash2,
  drag: LuGripVertical,
  menu: LuMenu,
  close: LuX,
  summary: LuFileText,
  contact: LuContact,
  experience: LuBriefcase,
  projects: LuFolderKanban,
  skills: LuCodeXml,
  languages: LuLanguages,
  education: LuGraduationCap,
  certifications: LuAward,
  history: LuHistory,
} as const;
